micronaut:
  application:
    name: administrationbe

datasources:
  default:
    url: ${APP_URL:`jdbc:postgresql://localhost:5432/administration`}
    username: ${APP_USERNAME:postgres}
    password: ${APP_PASSWORD:paula@123}
    driverClassName: org.postgresql.Driver
---
jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: false
flyway:
  datasources:
    default:
      enabled: true
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 1